version: '2'
services:
  nginx-php:
    image: debiannginxphp7:2.0
    ports:
     - "8080:80"
    volumes:
     - ../:/var/www/html/
    env_file: ../.env
#to run
#docker-compose -f docker-compose.yml up